# Generated by Django 4.0.6 on 2022-07-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
    ]
