# Generated by Django 4.0.6 on 2022-07-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_provinces'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provinces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.provinces'),
        ),
    ]
