# Generated by Django 4.0.6 on 2022-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
