# Generated by Django 4.0.6 on 2022-07-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customuser_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_updated',
            new_name='updated',
        ),
    ]
