# Generated by Django 4.0.6 on 2022-07-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_date_updated_customuser_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
